{{- if .Values.backend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "querymind.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "querymind.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: 8080
  selector:
    {{- include "querymind.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end -}}
